# generated-from:8e00a406fe64314786fe91ca66cb20ee864e4f95ce4ec9f6611623fae7ea6db3 DO NOT REMOVE, DO UPDATE

ACHGateway:
  Admin:
    BindAddress: ":9494"
  Telemetry:
    ServiceName: "achgateway"
  Inbound:
    HTTP:
      BindAddress: ":8484"
  # Database:
  #   DatabaseName: "achgateway"
  #   MySQL:
  #     Address: "tcp(localhost:3306)"
  #     User: "achgateway"
  #     Password: "achgateway"
